sort out bash script in mess

diff --git a/tool/4linux/bashrc b/tool/4linux/bashrc
--- a/tool/4linux/bashrc
+++ b/tool/4linux/bashrc
@@ -58,9 +58,12 @@ alias "mvelshell=java -jar  mvel2-2.0.12.jar"
 
 
 #function specfic to REDHAT
-#create a fast profile
+#create a dev profile
 function brmsenv()
 {
+  [[ "$1" == "--help" ]] && echo   "Usage:
+  1) brmsenv --To  create a new default profile
+  2)brmsenv fast --To create a new default profile and remove some service"
 
   #notice that error if add *whitespace* in 'BRMS53_ROOT_PATH= "brms-standalone-5.3.0"'
   BRMS53_ROOT_PATH="brms-standalone-5.3.0" 
@@ -75,69 +78,78 @@ function brmsenv()
     JBOSS_ROOT_PATH="$(expr substr $PWD 1 $i)/jboss-as"
   fi
 
-    FAST_PROFILE_PATH=$JBOSS_ROOT_PATH/server/fast
+    DEFAULT_PROFILE_PATH=$JBOSS_ROOT_PATH/server/default
+    BAK_PROFILE_PATH=$JBOSS_ROOT_PATH/server/BAK
 
   #copy default proile to fast profile, delete if already existed
-  [[ -d "$FAST_PROFILE_PATH" ]] && rm -rf $FAST_PROFILE_PATH
-  cp -r $JBOSS_ROOT_PATH/server/default $JBOSS_ROOT_PATH/server/fast
+  [[ ! -d "$BAK_PROFILE_PATH" ]] && cp -r $DEFAULT_PROFILE_PATH $BAK_PROFILE_PATH 
+  [[ -d "$BAK_PROFILE_PATH" ]] && rm -rf $DEFAULT_PROFILE_PATH
+  cp -r $BAK_PROFILE_PATH $DEFAULT_PROFILE_PATH
   
   #set brms auth
-  sed -i 's/#//g' $FAST_PROFILE_PATH/conf/props/brms-users.properties
+  sed -i 's/#//g' $DEFAULT_PROFILE_PATH/conf/props/brms-users.properties
 
   #set log, no append
-  sed -i 's/name="Append" value="true"/name="Append" value="false"/g' $FAST_PROFILE_PATH/conf/jboss-log4j.xml
+  sed -i 's/name="Append" value="true"/name="Append" value="false"/g' $DEFAULT_PROFILE_PATH/conf/jboss-log4j.xml
   
   #remove unused service and module
-  echo "Remove ejb3 service"
-  rm -f $FAST_PROFILE_PATH/deploy/ejb3*
-  rm -f $FAST_PROFILE_PATH/deployers/ejb3-deployers-jboss-beans.xml  $FAST_PROFILE_PATH/deployers/jboss-ejb3-endpoint-deployer.jar
+  if [ "$1" == "fast" ]; then
+    echo "Remove ejb3 service"
+    rm -f $DEFAULT_PROFILE_PATH/deploy/ejb3*
+    rm -f $DEFAULT_PROFILE_PATH/deployers/ejb3-deployers-jboss-beans.xml  $DEFAULT_PROFILE_PATH/deployers/jboss-ejb3-endpoint-deployer.jar
 
-  echo "Remove ejb2 service"
-  rm -f $FAST_PROFILE_PATH/deploy/ejb2*
+    echo "Remove ejb2 service"
+    rm -f $DEFAULT_PROFILE_PATH/deploy/ejb2*
 
 
-  echo "Remove key generator " 
-  rm -rf $FAST_PROFILE_PATH/deploy/uuid-key-generator.sar
+    echo "Remove key generator " 
+    rm -rf $DEFAULT_PROFILE_PATH/deploy/uuid-key-generator.sar
 
-  echo "Remove JBOSS MAIL" 
-  rm -rf $FAST_PROFILE_PATH/deploy/mail-service.xml $FAST_PROFILE_PATH/deploy/mail-ra.rar
+    echo "Remove JBOSS MAIL" 
+    rm -rf $DEFAULT_PROFILE_PATH/deploy/mail-service.xml $DEFAULT_PROFILE_PATH/deploy/mail-ra.rar
 
-  echo "removed seam & admin-console"
-  rm -rf $FAST_PROFILE_PATH/deploy/admin-console.war 
-  rm -rf $FAST_PROFILE_PATH/deployers/seam.deployer $FAST_PROFILE_PATH/deployers/webbeans.deployer 
+    echo "removed seam & admin-console"
+    rm -rf $DEFAULT_PROFILE_PATH/deploy/admin-console.war 
+    rm -rf $DEFAULT_PROFILE_PATH/deployers/seam.deployer $DEFAULT_PROFILE_PATH/deployers/webbeans.deployer 
 
-  echo "Removed xnio-deployer and xnio-provider"
-  rm -rf $FAST_PROFILE_PATH/deployers/xnio.deployer  $FAST_PROFILE_PATH/deploy/xnio-provider.jar
+    echo "Removed xnio-deployer and xnio-provider"
+    rm -rf $DEFAULT_PROFILE_PATH/deployers/xnio.deployer  $DEFAULT_PROFILE_PATH/deploy/xnio-provider.jar
 
-  echo "hot deployment"
-  rm -f $FAST_PROFILE_PATH/deploy/hdscanner-jboss-beans.xml
+    echo "hot deployment"
+    rm -f $DEFAULT_PROFILE_PATH/deploy/hdscanner-jboss-beans.xml
 
-  #remove jmx console and remoting and other stuff
-  echo "remove jmx console and remoting and other stuff"
-  rm -rf  $FAST_PROFILE_PATH/deploy/jmx-remoting.sar
-  rm -rf  $FAST_PROFILE_PATH/deploy/jmx-console.war
-  rm -rf  $FAST_PROFILE_PATH/deploy/profleservice-secured.jar
-  rm -rf  $FAST_PROFILE_PATH/deployers/sqlexception-service.xml
-  rm -rf  $FAST_PROFILE_PATH/deployers/hibernate-deployer-jboss-beans.xml 
- 
-  #echo "Remove JMS service" 
-  #rm -rf $FAST_PROFILE_PATH/deploy/quartz-ra.rar $FAST_PROFILE_PATH/deploy/jms-ra.rar
+    #remove jmx console and remoting and other stuff
+    echo "remove jmx console and remoting and other stuff"
+    rm -rf  $DEFAULT_PROFILE_PATH/deploy/jmx-remoting.sar
+    rm -rf  $DEFAULT_PROFILE_PATH/deploy/jmx-console.war
+    rm -rf  $DEFAULT_PROFILE_PATH/deploy/profleservice-secured.jar
+    rm -rf  $DEFAULT_PROFILE_PATH/deployers/sqlexception-service.xml
+    rm -rf  $DEFAULT_PROFILE_PATH/deployers/hibernate-deployer-jboss-beans.xml 
+   
+    #echo "Remove JMS service" 
+    #rm -rf $DEFAULT_PROFILE_PATH/deploy/quartz-ra.rar $DEFAULT_PROFILE_PATH/deploy/jms-ra.rar
+  fi
 
 }
 
 #General function 
-
+function assertEqual()
+{
+  [ $# -ne 2 ] && echo "Usage:$0 arg1 arg2"
+  test $1 -eq $2 2>/dev/null
+  #return 0 means success and true
+  [ $? -ne 0 ] && echo "Line:${LINENO} assertEquals failed! expected: $1 but was: $2 "
+}
 #
 function mytop()
 {
   [[ -z "$1" ]] && echo "Usage: mytop <process_name>" && return
   PIDS=""
   #head -n -1 to print all but the last one
-  for i in $(ps au|grep $1 |head -n -1 |awk '{print $2}');
+  for i in $(ps aux|grep $1 |head -n -1 |awk '{print $2}');
     do PIDS+="$i,"
   done
   PIDS+="0"
-  echo $PIDS
   top -p $PIDS
 }
 
@@ -175,7 +187,7 @@ function killit()
   #use tail , or awk 'NR!=1 && ${print $1}'
   #tail -n +2 print from the second line
 #  for i in $(ps -C $1 |tail -n +2 |awk '{print $1}');
-  for i in $(ps au|grep $1 |head -n -1 |awk '{print $2}');
+  for i in $(ps aux|grep $1 |head -n -1 |awk '{print $2}');
     do kill -9 $i;    echo " killed $i";
   done
   
@@ -235,7 +247,7 @@ function rgit()
 {
     (( $# == 0 )) && echo "Usage: $0 <git-cmd> ... [Run git command recursively over subdirs]" && return 1
 
-    setopt LOCAL_OPTIONS NO_ALL_EXPORT NO_AUTO_PUSHD
+    #setopt LOCAL_OPTIONS NO_ALL_EXPORT NO_AUTO_PUSHD
 
     local cwd=`pwd`
 
